### ISSUE TITLE
the right approach to add background

### ISSUE THREAD

**Issue by Abilet** [eymengunay/php-passbook#94] opened 2022-07-26 08:36 UTC
(Event ticket))
I do it this way, but background not showing up. Could you help ?

$background= new Image(BACKGROUND, 'background');
$pass->addImage($background);

**Comment by razvanphp** [comment] 2023-12-15 09:01
Maybe a duplicate of #68 ? Let's track this issue there. Thank you!

**Closed by razvanphp** 2023-12-15 09:01 UTC
