### ISSUE TITLE
PHP 8.1 deprecation warnings

### ISSUE THREAD

**Issue by cfreear** [eymengunay/php-passbook#91] opened 2022-02-09 11:44 UTC
PHP Deprecated:  Return type of Passbook\Pass\Image::getExtension() should either be compatible with SplFileInfo::getExtension(): string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice.

**Comment by eymengunay** [comment] 2022-02-12 11:41
Dear @cfreear 

Thank you for bringing this to attention. I haven't been doing any active maintenance of this repo since a while except for reviewing and accepting submitted pull requests.

It'll be much appreciated if you can submit a PR that fixes it.

Thank you.

**Comment by razvanphp** [comment] 2023-12-15 09:37
Fixed in PR #99 and released as [v3.1.2](https://github.com/eymengunay/php-passbook/releases/tag/v3.1.2)

Duplicate of #97

**Closed by razvanphp** 2023-12-15 09:37 UTC
